apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      affinity:
        nodeAffinity:
 {{- if .Values.global.affinity.requiredaffinity.enabled }}
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "provider.cubepaas.com/driver"
                operator: In
                values:
                - {{ .values.global.affinity.requiredaffinity.values }}
{{- end }}
 {{- if .Values.global.affinity.preferenceaffinity.enabled }}
           preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: "provider.cubepaas.com/driver"
                operator: In
                values:
                - {{ .values.global.affinity.preferenceaffinity.values }}
{{- end }}
  {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
  {{- end }}
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: {{ .Values.service.port }}
        resources:
          limits:
            cpu: 300m
            memory: 800Mi
          requests:
            cpu: 100m
            memory: 200Mi