apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql-secret
type: Opaque
data:
    mysql-password: {{ .Values.mysqlPassword | toString | b64enc | quote }}
    mysql-user: {{ .Values.mysqlUser | toString | b64enc | quote }}